#pragma once

enum OBJID  { OBJ_PLAYER,OBJ_PLAYER_WORLD, OBJ_BULLET,OBJ_MONSTER_BULLET,OBJ_PARRY, OBJ_MONSTER, OBJ_MOUSE, OBJ_EFFECT,OBJ_UI, OBJ_BUTTON,OBJ_WALL, OBJ_CLOUD, OBJ_END };

enum DIR	{ DIR_LEFT, DIR_UP, DIR_RIGHT, DIR_DOWN, DIR_LU, DIR_RU,DIR_RD,DIR_LD, DIR_END };

enum DIRECTION { LEFT, RIGHT, END };

enum SCENEID {SC_LOGO, SC_MENU, SC_EDIT,SC_STAGEWORLD,SC_STAGETUTORIAL, SC_STAGEROOT, SC_STAGEFIRST, SC_STAGESECOND, SC_STAGEBOSS_2, SC_END };

enum RENDERID {BACKGROUND, BOSSSTAGE, GAMEOBJECT, EFFECT, UI, RENDER_END };

enum CHANNELID { SOUND_EFFECT, SOUND_BGM, SOUND_PLAYER, SOUND_MONSTER, MAXCHANNEL };

enum LOOK { LOOK_LEFT, LOOK_RIGHT,LOOK_RU, LOOK_LU,LOOK_RD,LOOK_LD,LOOK_DOWN,LOOK_UP, LOOK_END };

enum OBJECTSTATE { AIR, GROUND,FALL, OBJECTSTATE_END};

enum MONSTER_INPUT {MON_LEFT, MON_RIGHT, MON_JUMP, MON_ATTACK};

enum MONSTER_BULLET_TYPE { DROP, CHASER, PARRY, MBTYPE_END };

